import os

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle
)

from reportlab.lib import colors

from reportlab.lib.styles import (
    getSampleStyleSheet
)


def generate_pdf_report(
    analysis,
    summary,
    executive_summary,
    remediation_report
):

    os.makedirs(
        "pdf_reports",
        exist_ok=True
    )

    report_path = (
        "pdf_reports/kubeguardian_report.pdf"
    )

    doc = SimpleDocTemplate(
        report_path
    )

    styles = getSampleStyleSheet()

    content = []

    # ==================================================
    # COVER PAGE
    # ==================================================

    content.append(
        Paragraph(
            "KubeGuardian AI",
            styles["Title"]
        )
    )

    content.append(
        Paragraph(
            "Infrastructure Security Assessment Report",
            styles["Heading2"]
        )
    )

    content.append(
        Spacer(1, 30)
    )

    content.append(
        Paragraph(
            f"Security Score: {analysis['score']}/100",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by KubeGuardian AI",
            styles["BodyText"]
        )
    )

    content.append(
        PageBreak()
    )

    # ==================================================
    # FINDINGS SUMMARY
    # ==================================================

    content.append(
        Paragraph(
            "Findings Summary",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    summary_table = Table(
        [
            ["Severity", "Count"],
            ["Critical", summary["critical"]],
            ["High", summary["high"]],
            ["Medium", summary["medium"]],
            ["Low", summary["low"]]
        ],
        colWidths=[150, 100]
    )

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold")
        ])
    )

    content.append(summary_table)

    content.append(
        Spacer(1, 20)
    )

    # ==================================================
    # EXECUTIVE SUMMARY
    # ==================================================

    content.append(
        Paragraph(
            "Executive Summary",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    content.append(
        Paragraph(
            executive_summary.replace("\n", "<br/>"),
            styles["BodyText"]
        )
    )

    content.append(
        PageBreak()
    )

    # ==================================================
    # DETAILED FINDINGS
    # ==================================================

    content.append(
        Paragraph(
            "Detailed Findings",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    for finding in analysis["findings"]:

        content.append(
            Paragraph(
                finding["rule"],
                styles["Heading2"]
            )
        )

        content.append(
            Paragraph(
                f"<b>Severity:</b> {finding['severity']}",
                styles["BodyText"]
            )
        )

        content.append(
            Paragraph(
                f"<b>Priority:</b> {finding['priority']}",
                styles["BodyText"]
            )
        )

        if "resource_name" in finding:

            content.append(
                Paragraph(
                    f"<b>Resource:</b> {finding['resource_name']}",
                    styles["BodyText"]
                )
            )

        content.append(
            Paragraph(
                f"<b>Risk:</b> {finding['risk']}",
                styles["BodyText"]
            )
        )

        content.append(
            Paragraph(
                f"<b>Impact:</b> {finding['impact']}",
                styles["BodyText"]
            )
        )

        content.append(
            Paragraph(
                f"<b>Recommended Fix:</b> {finding['recommended_fix']}",
                styles["BodyText"]
            )
        )

        content.append(
            Spacer(1, 15)
        )

    content.append(
        PageBreak()
    )

    # ==================================================
    # AI REMEDIATION REPORT
    # ==================================================

    content.append(
        Paragraph(
            "AI Remediation Report",
            styles["Heading1"]
        )
    )

    content.append(
        Spacer(1, 10)
    )

    # Clean markdown headings
    remediation_report = (
        remediation_report
        .replace("###", "")
        .replace("##", "")
        .replace("#", "")
    )

    for line in remediation_report.split("\n"):

        line = line.strip()

        if not line:
            continue

        content.append(
            Paragraph(
                line,
                styles["BodyText"]
            )
        )

    doc.build(content)

    return report_path